### ISSUE TITLE
您好，请问文件mention_extractor.py中tokens和mentions有什么区别？kbqa.process.data数据是您自己生成的吗？

### ISSUE THREAD

**Issue by johnson-xu01** [soloice/QA-System#2]

**Comment by soloice** [comment]
最近我比较忙，没有及时回复。

是这样的，kbqa.process.data 是修改了一下官方给的 baseline 对句子进行解析得到的 token/mention list 文件。

token 和 mention 的区别是，tokens 是对一个问题做分词以后的结果，比如“北京大学在哪里？”这句话，它的 token list 可能就是 `["北京大学", "在", "哪里", "？"]`。而 mention list 则是对句中所有命名实体进行解析，包含程序认为的所有的命名实体，因此可能会有部分重叠，比如上面这句话，mention list 可能就是 `["北京", "北京大学", "大学", "在", "在哪里", "哪里", "?"]`。

我稍等一会儿传一个 kbqa.process.data 上去，你看看那个文件就明白了。每一组数据里，第三行是 tokens，第四行是 mentions.

**Comment by xuyiqiang-learn** [comment]
好的，谢谢啦，请问您有博客地址吗？我想关注一些

**Comment by johnson-xu01** [comment]
好的，谢谢啦，请问您写博客吗？我想关注一下

**Comment by soloice** [comment]
不好意思，我不写博客

**Comment by johnson-xu01** [comment]
好的，谢谢

**Comment by soloice** [comment]
已上传。
